### ISSUE TITLE
Invalid `z-index` parameter for button

### ISSUE THREAD

**Issue by iamdanchi** [coingaming/moon#414]
Need to check `z-index` in different components. 
It’s not working now for button in modal form :disappointed:

https://coingaming.slack.com/files/U02UTEFCKM4/F046F7TPY7N/screen_recording_2022-10-13_at_15.49.27.mov

P.S. It was fixed in this [PR](https://github.com/coingaming/moon/pull/376), but not working in current version

**Comment by phgrey** [comment]
@iamdanchi can u please provide modal from code sample?

**Comment by iamdanchi** [comment]
I check it again, it's working, all is good. Maybe someone already fixed it
