### ISSUE TITLE
Use class only for less confusion

### ISSUE THREAD

**Issue by margusp2heathmont** [coingaming/moon#474]
Currently we have problem, that in some cases, we use

`<Element class="some properties" other_prop_with_default_value="other-value" />`

It is a bit not intuitive. React has different implementation. Where default props are just replaced in string. 

Todo: Test efficiency (render speed with one or another approach?)

**Comment by phgrey** [comment]
I got the approach. not sure if any stress-testing/profiling  is needed - alghoritm has complecity O(N), where N - number of classes.
But implemeting as a helper will be not so comfortable in usage. @margusp2heathmont , What do you think - can we make a new prop_type for Surface - moon_class, cloning & updating css_class?

**Comment by margusp2heathmont** [comment]
https://github.com/bratsche/twix addresses this

**Comment by margusp2heathmont** [comment]
There is also this discussion going on (that references other library and integration into LiveViews) https://github.com/phoenixframework/phoenix_live_view/pull/2366

**Comment by phgrey** [comment]
https://github.com/coingaming/moon/tree/MDS-317-2 - branch with first try of twix (mergeClass tests are broken)
https://github.com/bratsche/twix/issues/7 - issue on a  twix itself

**Comment by bratsche** [comment]
It also kind of looks like this is what you need. Am I understanding your setup correctly? https://github.com/bratsche/twix/issues/6

**Comment by phgrey** [comment]
looks like current twix-free implementation is good enough for using
