### ISSUE TITLE
Locating Moon Surface Themes

### ISSUE THREAD

**Issue by KennyTron** [coingaming/moon#475]
Hello, I'm interested in using Moon with a new Elixir Phoenix project after reading about it on the Elixir forums. Following the getting started guide and it seems like there are a few steps missing. Was able to poke around a bit and get some aspects up and running but having trouble finding/generating the css referenced in the `Moon CSS assets adding` step.

```
<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/moon/assets/css/lab-dark.css") %>" />
<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/moon/assets/css/lab-light.css") %>" />
```

Where do the style sheets `/moon/assets/css/lab-dark.css` exist / how are they generated? I'm also wondering if there are any sample projects you could point me towards to learn more about setting up a project for Moon?

Thank you.

**Comment by margusp2heathmont** [comment]
https://github.com/coingaming/moon/tree/main/priv/static/themes
