### ISSUE TITLE
Decrease number of files in project

### ISSUE THREAD

**Issue by phgrey** [coingaming/moon#503]
Problems: 
 - project is compiling (or recompiling) too long, incl. vscode's analyzer
 - impossible to run debugger
 
Suggested solution:
move flags & icons (*.ex files containing svg data) to separate library, e.g. moon-icons-ex

@margusp2heathmont what do you thinking about it?

**Comment by margusp2heathmont** [comment]
1. I think new Elixir version compiler should be smarter
2. Also there should be some configuration params, if something changed, what files are recompiled (not all)

If 1-2 and do not help, we can make a new package. If there is architectural/process reason why we want new package for icons-flags, we can do it, but slow compile should be solved with 1 or 2.

**Comment by phgrey** [comment]
1. did not found any updates about it on elixir_1.14 release notes, and not sure if 1.13 -> 1.14 update will do the trick ((( but anyway, updating elixir version is a good idea anyway, thanks
2. common mix compile config is only about the per-environment directory list. not sure if it's a good place for smart-and-unobvious solutions.
